### ISSUE TITLE
models: create initial database model

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-sipstore#1]
Create basic initial SQLAlchemy model - something like this:

SIP:
- id (uuid)
- format
- content
- timestamp
- user_id
- ip_address
- email_address

SIPFiles
- sip_id
- filename
- file_id

RecordSIP
- sip_id
- pid_type
- pid_value

**Comment by krzysztof** [comment]
``SIPFiles`` -> ``FileSIP`` ?

**Comment by krzysztof** [comment]
Should ``user_id``, ``ip_address`` and ``email_address`` be a single field ``agent`` or more general ``info`` with a JSONType ?
This way more could be contained (browser info, request parameters, geospatial ?), depending on what would be required in a given use-case.

**Comment by krzysztof** [comment]
Is ``FileSIP.file_id`` a FK to ``FileInstance.id`` ?
Should ``RecordSIP.pid_id -> db.FK(PersistenIdentifier.id)`` also exist ?

**Comment by lnielsen** [comment]
> SIPFiles -> FileSIP ?

I would go with ``SIPFile``. It's the SIP's File. For ``RecordSIP``, it's the Record's SIP.

> Should user_id, ip_address and email_address be a single field agent or more general info with a JSONType ?
> This way more could be contained (e.g.: browser info, request parameters, geolocation data), depending on what would be required in a given use-case.

Perhaps split into user_id (FK, nullable) and agent (JSON, whatever extra you want to store about a user) so that we more easily can do  joins?

> Is FileSIP.file_id a FK to FileInstance.id ?

Yes

> Should RecordSIP.pid_id -> db.FK(PersistenIdentifier.id) also exist?

Yes, probably better and just remove pid_type/pid_value

**Comment by kaplun** [comment]
> Perhaps split into user_id (FK, nullable) and agent (JSON, whatever extra you want to store about a user) so that we more easily can do joins?

How do you express harvested content (i.e. where there is no real user involved, albeit indeed an agent)?

**Comment by krzysztof** [comment]
In that case the ``user_id`` would be null, and the ``agent`` JSON, controlled by a jsonschema, can be as explicit about the harvesting agent as necessary.
